### PR TITLE
Knet miner ui

### PR DESCRIPTION
**Pull request by Monika-Mistry**

### CODE REVIEW

**Comment by AjitPS** [comment]
@Monika-Mistry can you comment what changes this includes, besides edited `releaseNotes` ? Thanks

**Comment by AjitPS** [comment]
Also, I noticed a lot of edits to Barley. When does this need to be re-deployed?

**Comment by Monika-Mistry** [comment]
I've updated the release notes to ensembl 36 for the networks I'm building now.

**Comment by Monika-Mistry** [comment]
There's a new Barley genome released with ensembl 36. I'll need to test this first

**Comment by AjitPS** [comment]
ok

**Pull request merged**
